version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.1
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 7.0.0
    - 7.0.1
    - 7.0.7
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: victory
    versions:
    - 35.4.11
    - 35.4.12
    - 35.4.13
    - 35.4.6
    - 35.4.7
    - 35.4.8
    - 35.4.9
    - 35.5.0
  - dependency-name: "@prisma/client"
    versions:
    - 2.15.0
    - 2.16.1
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.1
  - dependency-name: "@prisma/cli"
    versions:
    - 2.15.0
    - 2.16.1
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: little-state-machine
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: joi
    versions:
    - 17.3.0
